if(NOT DEFINED TEMPLATE OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "TEMPLATE and OUTPUT are required")
endif()
file(READ "${TEMPLATE}" _contents)
function(define_value _name _value)
  string(REGEX REPLACE "#undef ${_name}([^A-Za-z0-9_])"
    "#define ${_name} ${_value}\\1" _new_contents "${_contents}")
  set(_contents "${_new_contents}" PARENT_SCOPE)
endfunction()
define_value(ALIGNOF_DOUBLE 8)
define_value(ALIGNOF_INT 4)
define_value(ALIGNOF_LONG 8)
define_value(ALIGNOF_LONG_LONG_INT 8)
define_value(ALIGNOF_SHORT 2)
define_value(ACCEPT_TYPE_ARG3 socklen_t)
define_value(BLCKSZ "${BLCKSZ}")
define_value(DEF_PGPORT "${DEF_PGPORT}")
define_value(DEF_PGPORT_STR "\"${DEF_PGPORT}\"")
define_value(FLOAT4PASSBYVAL true)
define_value(FLOAT8PASSBYVAL true)
define_value(USE_FLOAT4_BYVAL 1)
define_value(USE_FLOAT8_BYVAL 1)
define_value(FLEXIBLE_ARRAY_MEMBER 1)
define_value(GP_MAJORVERSION "\"${GP_MAJORVERSION}\"")
define_value(GP_VERSION "\"${GP_VERSION}\"")
define_value(GP_VERSION_NUM ${GP_VERSION_NUM})
define_value(PG_VERSION "\"${PG_VERSION_VALUE}\"")
define_value(PG_MAJORVERSION "\"${PG_MAJORVERSION_VALUE}\"")
define_value(PG_VERSION_NUM ${PG_VERSION_NUM_VALUE})
define_value(PG_VERSION_STR
             "\"PostgreSQL ${PG_VERSION_VALUE} (Greenplum Database ${GP_VERSION})\"")
define_value(PG_PRINTF_ATTRIBUTE printf)
# `restrict` is valid C99 but is not a C++ keyword.  The LLVM provider is
# compiled as C++, so use the compiler extension accepted by both Clang and
# GCC for the generated headers consumed by C and C++ sources.
define_value(pg_restrict __restrict)
define_value(PG_KRB_SRVNAM "\"postgres\"")
define_value(PACKAGE_NAME "\"PomeloDB\"")
define_value(PACKAGE_VERSION "\"${GP_VERSION}\"")
define_value(PACKAGE_STRING "\"PomeloDB ${GP_VERSION}\"")
define_value(PACKAGE_BUGREPORT "\"https://github.com/vanashia/PolemoDB/issues\"")
define_value(MAXIMUM_ALIGNOF 8)
define_value(ALIGNOF_PG_INT128_TYPE 16)
define_value(PG_INT128_TYPE __int128)
define_value(PG_INT64_TYPE long)
define_value(RELSEG_SIZE ${RELSEG_SIZE})
define_value(SIZEOF_BOOL 1)
define_value(SIZEOF_DATUM 8)
define_value(SIZEOF_LONG 8)
define_value(SIZEOF_OFF_T 8)
define_value(SIZEOF_SIZE_T 8)
define_value(SIZEOF_VOID_P 8)
define_value(XLOG_BLCKSZ ${XLOG_BLCKSZ})
define_value(HAVE_STDBOOL_H 1)
define_value(HAVE_STDINT_H 1)
define_value(HAVE_STDLIB_H 1)
define_value(HAVE_STRING_H 1)
define_value(HAVE_STRINGS_H 1)
define_value(HAVE_UNISTD_H 1)
define_value(HAVE_WCHAR_H 1)
define_value(HAVE_WCTYPE_H 1)
define_value(HAVE_SYS_TYPES_H 1)
define_value(HAVE_SYS_STAT_H 1)
define_value(HAVE_SYS_SELECT_H 1)
define_value(HAVE_SYS_RESOURCE_H 1)
define_value(HAVE_SYS_IPC_H 1)
define_value(HAVE_SYS_SEM_H 1)
define_value(HAVE_SYS_SHM_H 1)
define_value(HAVE_SYS_UN_H 1)
define_value(HAVE_NET_IF_H 1)
define_value(HAVE_NETINET_TCP_H 1)
define_value(HAVE_IFADDRS_H 1)
define_value(HAVE_ISINF 1)
define_value(HAVE_POLL_H 1)
define_value(HAVE_POLL 1)
define_value(HAVE_GETADDRINFO 1)
define_value(HAVE_GETRUSAGE 1)
define_value(HAVE_STRUCT_ADDRINFO 1)
define_value(HAVE_STRUCT_SOCKADDR_STORAGE 1)
define_value(HAVE_STRUCT_SOCKADDR_STORAGE_SS_FAMILY 1)
define_value(HAVE_STRUCT_SOCKADDR_SA_LEN 1)
define_value(HAVE_STRUCT_TM_TM_ZONE 1)
define_value(HAVE_GETIFADDRS 1)
define_value(HAVE_GETOPT 1)
define_value(HAVE_GETOPT_H 1)
define_value(HAVE_GETOPT_LONG 1)
define_value(HAVE_STRUCT_OPTION 1)
define_value(HAVE_FUNCNAME__FUNC 1)
define_value(HAVE_INET_ATON 1)
define_value(HAVE_INET_NTOP 1)
define_value(HAVE_IPV6 1)
define_value(HAVE_UNIX_SOCKETS 1)
define_value(HAVE_PTHREAD 1)
define_value(HAVE_PTHREAD_PRIO_INHERIT 1)
define_value(HAVE_SPINLOCKS 1)
define_value(HAVE_SYMLINK 1)
if(DEFINED HAVE_READLINK AND HAVE_READLINK)
  define_value(HAVE_READLINK 1)
endif()
define_value(HAVE_MKDTEMP 1)
define_value(HAVE_MEMMOVE 1)
define_value(HAVE_FDATASYNC 1)
define_value(HAVE_FSEEKO 1)
define_value(HAVE_PREAD 1)
define_value(HAVE_PWRITE 1)
define_value(HAVE_RANDOM 1)
define_value(HAVE_SETENV 1)
define_value(HAVE_UNSETENV 1)
define_value(HAVE_SSL_GET_CURRENT_COMPRESSION 1)
define_value(HAVE_SRANDOM 1)
if(DEFINED HAVE_STRERROR_R AND HAVE_STRERROR_R)
  define_value(HAVE_STRERROR_R 1)
endif()
if(DEFINED STRERROR_R_INT AND STRERROR_R_INT)
  define_value(STRERROR_R_INT 1)
endif()
if(DEFINED HAVE_LOCALE_T AND HAVE_LOCALE_T)
  define_value(HAVE_LOCALE_T 1)
endif()
define_value(MEMSET_LOOP_LIMIT 1024)
define_value(HAVE_STRLCAT 1)
define_value(HAVE_STRLCPY 1)
define_value(HAVE_DECL_STRLCAT 1)
define_value(HAVE_DECL_STRLCPY 1)
define_value(HAVE_DECL_STRNLEN 1)
define_value(HAVE_LONG_INT_64 1)
define_value(HAVE_STRTOF 1)
define_value(HAVE_STRTOLL 1)
define_value(HAVE_STRTOULL 1)
define_value(HAVE_STRNLEN 1)
define_value(HAVE_STRLCPY 1)
define_value(HAVE_STRLCAT 1)
define_value(HAVE_CLOCK_GETTIME 1)
define_value(HAVE_DECL_F_FULLFSYNC 1)
define_value(HAVE_BSWAP64 1)
define_value(HAVE_BACKTRACE_SYMBOLS 1)
define_value(HAVE_EXECINFO_H 1)
define_value(HAVE_ATOMICS 1)
define_value(HAVE_GCC__SYNC_CHAR_TAS 1)
define_value(HAVE_GCC__SYNC_INT32_CAS 1)
define_value(HAVE_GCC__SYNC_INT64_CAS 1)
define_value(HAVE__BUILTIN_BSWAP16 1)
define_value(HAVE__BUILTIN_BSWAP32 1)
define_value(HAVE__BUILTIN_BSWAP64 1)
define_value(HAVE__BUILTIN_CLZ 1)
define_value(HAVE__BUILTIN_CTZ 1)
define_value(HAVE__BUILTIN_POPCOUNT 1)
define_value(HAVE__BUILTIN_UNREACHABLE 1)
define_value(HAVE_GCC_INT_ATOMICS 1)
define_value(HAVE_GCC__SYNC_INT32_TAS 1)
define_value(INT64_MODIFIER "\"l\"")
define_value(HAVE_GCC__ATOMIC_INT32_CAS 1)
define_value(HAVE_GCC__ATOMIC_INT64_CAS 1)
define_value(HAVE_COMPUTED_GOTO 1)
define_value(HAVE_TYPEOF 1)
define_value(HAVE__STATIC_ASSERT 1)
if(DEFINED ENABLE_GSS AND ENABLE_GSS)
  define_value(ENABLE_GSS 1)
endif()
if(DEFINED HAVE_GSSAPI_GSSAPI_H AND HAVE_GSSAPI_GSSAPI_H)
  define_value(HAVE_GSSAPI_GSSAPI_H 1)
endif()
if(DEFINED HAVE_LIBBZ2 AND HAVE_LIBBZ2)
  define_value(HAVE_LIBBZ2 1)
endif()
if(DEFINED HAVE_LIBREADLINE AND HAVE_LIBREADLINE)
  define_value(HAVE_LIBREADLINE 1)
endif()
if(DEFINED HAVE_READLINE_HISTORY_H AND HAVE_READLINE_HISTORY_H)
  define_value(HAVE_READLINE_HISTORY_H 1)
endif()
if(DEFINED HAVE_READLINE_READLINE_H AND HAVE_READLINE_READLINE_H)
  define_value(HAVE_READLINE_READLINE_H 1)
endif()
if(DEFINED HAVE_LIBSSL AND HAVE_LIBSSL)
  define_value(HAVE_LIBSSL 1)
endif()
if(DEFINED HAVE_UNION_SEMUN AND HAVE_UNION_SEMUN)
  define_value(HAVE_UNION_SEMUN 1)
endif()
if(DEFINED HAVE_CRYPT AND HAVE_CRYPT)
  define_value(HAVE_CRYPT 1)
endif()
if(DEFINED HAVE_RINT AND HAVE_RINT)
  define_value(HAVE_RINT 1)
endif()
if(DEFINED HAVE_DLOPEN AND HAVE_DLOPEN)
  define_value(HAVE_DLOPEN 1)
endif()
if(DEFINED HAVE_STRCHRNUL AND HAVE_STRCHRNUL)
  define_value(HAVE_STRCHRNUL 1)
endif()
if(DEFINED HAVE_FLS AND HAVE_FLS)
  define_value(HAVE_FLS 1)
endif()
if(DEFINED HAVE_GETPEEREID AND HAVE_GETPEEREID)
  define_value(HAVE_GETPEEREID 1)
endif()
if(DEFINED HAVE_LIBZ AND HAVE_LIBZ)
  define_value(HAVE_LIBZ 1)
endif()
if(DEFINED HAVE_SHM_OPEN AND HAVE_SHM_OPEN)
  define_value(HAVE_SHM_OPEN 1)
endif()
if(DEFINED ENABLE_THREAD_SAFETY AND ENABLE_THREAD_SAFETY)
  define_value(ENABLE_THREAD_SAFETY 1)
endif()
if(DEFINED USE_ICU AND USE_ICU)
  define_value(USE_ICU 1)
endif()
if(DEFINED USE_LIBXML AND USE_LIBXML)
  define_value(USE_LIBXML 1)
endif()
if(DEFINED USE_CURL AND USE_CURL)
  define_value(USE_CURL 1)
endif()
if(DEFINED USE_LLVM AND USE_LLVM)
  define_value(USE_LLVM 1)
endif()
if(DEFINED USE_LDAP AND USE_LDAP)
  define_value(USE_LDAP 1)
endif()
if(DEFINED HAVE_LDAP_H AND HAVE_LDAP_H)
  define_value(HAVE_LDAP_H 1)
endif()
if(DEFINED HAVE_LDAP_INITIALIZE AND HAVE_LDAP_INITIALIZE)
  define_value(HAVE_LDAP_INITIALIZE 1)
endif()
if(DEFINED HAVE_LIBLDAP AND HAVE_LIBLDAP)
  define_value(HAVE_LIBLDAP 1)
endif()
if(DEFINED USE_OPENSSL AND USE_OPENSSL)
  define_value(USE_OPENSSL 1)
  define_value(HAVE_BIO_GET_DATA 1)
  define_value(HAVE_BIO_METH_NEW 1)
endif()
if(DEFINED USE_OPENSSL_RANDOM AND USE_OPENSSL_RANDOM)
  define_value(USE_OPENSSL_RANDOM 1)
endif()
if(DEFINED USE_DEV_URANDOM AND USE_DEV_URANDOM)
  define_value(USE_DEV_URANDOM 1)
endif()
if(DEFINED USE_ZSTD AND USE_ZSTD)
  define_value(USE_ZSTD 1)
endif()
if(DEFINED USE_ORCA AND USE_ORCA)
  define_value(USE_ORCA 1)
endif()
if(DEFINED USE_ARMV8_CRC32C AND USE_ARMV8_CRC32C)
  define_value(USE_ARMV8_CRC32C 1)
endif()
if(DEFINED USE_SYSV_SEMAPHORES AND USE_SYSV_SEMAPHORES)
  define_value(USE_SYSV_SEMAPHORES 1)
endif()
if(DEFINED USE_SYSV_SHARED_MEMORY AND USE_SYSV_SHARED_MEMORY)
  define_value(USE_SYSV_SHARED_MEMORY 1)
endif()
if(DEFINED FAULT_INJECTOR AND FAULT_INJECTOR)
  define_value(FAULT_INJECTOR 1)
endif()
file(WRITE "${OUTPUT}" "${_contents}")
