include(CMakeParseArguments)

if(CMAKE_INSTALL_PREFIX_INITIALIZED_TO_DEFAULT)
  set(CMAKE_INSTALL_PREFIX "/usr/local/pomelodb" CACHE PATH
      "Install path prefix, prepended onto install directories." FORCE)
endif()

set(GPDB_PGPORT "5432" CACHE STRING "Default PostgreSQL port")
set(GPDB_BLOCKSIZE "32" CACHE STRING "Table block size in kB")
set(GPDB_SEGSIZE "1" CACHE STRING "Table segment size in GB")
set(GPDB_WAL_BLOCKSIZE "32" CACHE STRING "WAL block size in kB")
set(GPDB_EXTRA_VERSION "" CACHE STRING "Append a string to the GPDB version")
set(GPDB_APR_CONFIG "" CACHE FILEPATH "Compatibility path; APR is discovered natively")
set(GPDB_INCLUDES "" CACHE STRING "Additional include directories")
set(GPDB_LIBRARIES "" CACHE STRING "Additional library directories")
set(GPDB_CPPFLAGS "" CACHE STRING "Additional preprocessor flags")
set(GPDB_CFLAGS "" CACHE STRING "Additional C compiler flags")
set(GPDB_CXXFLAGS "" CACHE STRING "Additional C++ compiler flags")
set(GPDB_LDFLAGS "" CACHE STRING "Additional linker flags")

option(GPDB_ENABLE_RPATH "Enable runtime library paths" ON)
option(GPDB_ENABLE_SPINLOCKS "Use spinlocks" ON)
option(GPDB_ENABLE_ATOMICS "Use atomics" ON)
option(GPDB_ENABLE_STRONG_RANDOM "Use strong random source" ON)
option(GPDB_ENABLE_GPFDIST "Build gpfdist" ON)
option(GPDB_ENABLE_DEBUG_EXTENSIONS "Build fault-injection extensions" ON)
option(GPDB_ENABLE_DEBUG "Build debug configuration" OFF)
option(GPDB_ENABLE_CASSERT "Enable assertion checks" OFF)
option(GPDB_ENABLE_ORCA "Build ORCA optimizer" ON)
option(GPDB_ENABLE_IC_PROXY "Build interconnect proxy" OFF)
option(GPDB_ENABLE_THREAD_SAFETY "Build thread-safe client libraries" ON)
option(GPDB_ENABLE_INTEGER_DATETIMES "Use integer datetimes" ON)
option(GPDB_ENABLE_LARGEFILE "Use large files" ON)
option(GPDB_WITH_LLVM "Build LLVM JIT support" OFF)
option(GPDB_WITH_ICU "Build ICU support" OFF)
option(GPDB_WITH_TCL "Build PL/Tcl" OFF)
option(GPDB_WITH_PERL "Build PL/Perl" OFF)
option(GPDB_WITH_PYTHON "Build PL/Python" ON)
option(GPDB_WITH_GSSAPI "Build GSSAPI support" OFF)
option(GPDB_WITH_PAM "Build PAM support" OFF)
option(GPDB_WITH_BSD_AUTH "Build BSD authentication support" OFF)
option(GPDB_WITH_LDAP "Build LDAP support" OFF)
option(GPDB_WITH_BONJOUR "Build Bonjour support" OFF)
option(GPDB_WITH_OPENSSL "Build OpenSSL support" OFF)
option(GPDB_WITH_SELINUX "Build SELinux support" OFF)
option(GPDB_WITH_SYSTEMD "Build systemd support" OFF)
option(GPDB_WITH_READLINE "Build readline/libedit support" ON)
option(GPDB_WITH_LIBEDIT_PREFERRED "Prefer libedit over readline" OFF)
option(GPDB_WITH_LIBXML "Build XML support" OFF)
option(GPDB_WITH_LIBXSLT "Build XSLT support" OFF)
option(GPDB_WITH_ZLIB "Build zlib support" ON)
option(GPDB_WITH_LIBBZ2 "Build bzip2 support" ON)
option(GPDB_WITH_ZSTD "Build Zstandard support" ON)
option(GPDB_WITH_RT "Build realtime library support" ON)
option(GPDB_WITH_LIBCURL "Build libcurl support" ON)

if(GPDB_ENABLE_DEBUG)
  add_compile_definitions(USE_ASSERT_CHECKING)
endif()

set(GPDB_VERSION "7.0.0-beta.0" CACHE STRING "PomeloDB version")
set(GPDB_MAJOR_VERSION "7" CACHE STRING "PomeloDB major version")
set(GPDB_PG_VERSION "12.12" CACHE STRING "PostgreSQL compatibility version")

set(GPDB_INSTALL_BINDIR "${CMAKE_INSTALL_BINDIR}" CACHE PATH "PomeloDB binary directory")
set(GPDB_INSTALL_LIBDIR "${CMAKE_INSTALL_LIBDIR}" CACHE PATH "PomeloDB library directory")
set(GPDB_INSTALL_DATADIR "${CMAKE_INSTALL_DATADIR}/postgresql" CACHE PATH "PomeloDB shared data directory")
set(GPDB_INSTALL_INCLUDEDIR "${CMAKE_INSTALL_INCLUDEDIR}" CACHE PATH "PomeloDB include directory")

function(gpdb_apply_common_options _target)
  target_compile_features(${_target} PRIVATE c_std_99)
  target_compile_definitions(${_target} PRIVATE
    _GNU_SOURCE
    FLOAT4PASSBYVAL=true
    FLOAT8PASSBYVAL=true
    USE_FLOAT4_BYVAL
    USE_FLOAT8_BYVAL)
  if(GPDB_ENABLE_DEBUG_EXTENSIONS)
    target_compile_definitions(${_target} PRIVATE FAULT_INJECTOR)
  endif()
  if(GPDB_ENABLE_CASSERT)
    target_compile_definitions(${_target} PRIVATE USE_ASSERT_CHECKING GPOS_DEBUG)
  endif()
  if(GPDB_ENABLE_IC_PROXY)
    target_compile_definitions(${_target} PRIVATE ENABLE_IC_PROXY)
  endif()
  if(GPDB_WITH_GSSAPI)
    target_compile_definitions(${_target} PRIVATE ENABLE_GSS)
  endif()
  if(GPDB_WITH_OPENSSL)
    target_compile_definitions(${_target} PRIVATE USE_OPENSSL USE_OPENSSL_RANDOM)
  else()
    target_compile_definitions(${_target} PRIVATE USE_DEV_URANDOM)
  endif()
  if(GPDB_WITH_LIBXML)
    target_compile_definitions(${_target} PRIVATE USE_LIBXML)
  endif()
  if(GPDB_WITH_ZSTD)
    target_compile_definitions(${_target} PRIVATE USE_ZSTD)
  endif()
  if(GPDB_WITH_ZLIB)
    target_compile_definitions(${_target} PRIVATE HAVE_LIBZ)
  endif()
  if(GPDB_WITH_ICU)
    target_compile_definitions(${_target} PRIVATE USE_ICU)
  endif()
  if(GPDB_ENABLE_ORCA)
    target_compile_definitions(${_target} PRIVATE USE_ORCA)
  endif()
  if(GPDB_CPPFLAGS)
    separate_arguments(_extra_cppflags UNIX_COMMAND "${GPDB_CPPFLAGS}")
    target_compile_options(${_target} PRIVATE ${_extra_cppflags})
  endif()
  if(GPDB_CFLAGS)
    separate_arguments(_extra_cflags UNIX_COMMAND "${GPDB_CFLAGS}")
    target_compile_options(${_target} PRIVATE $<$<COMPILE_LANGUAGE:C>:${_extra_cflags}>)
  endif()
  if(GPDB_CXXFLAGS)
    separate_arguments(_extra_cxxflags UNIX_COMMAND "${GPDB_CXXFLAGS}")
    target_compile_options(${_target} PRIVATE $<$<COMPILE_LANGUAGE:CXX>:${_extra_cxxflags}>)
  endif()
endfunction()
